# frozen_string_literal: true

def filter_own(filelist)
  filelist
    .reject { |f| f =~ %r{/Vendor/} }
    .reject { |f| f =~ %r{/AutoGenerated/} }
    .reject { |f| f =~ %r{/GooglePlayGames/} }
    .reject { |f| f =~ %r{/Plugins/} }
end

task format: %i[format:cs format:ruby]

namespace :format do
  desc '*.csファイルを整形する'
  task :cs do
    srcs = filter_own(FileList[UNITY_PROJECT + 'Assets/**/*.cs'].to_a)
    srcs.each_slice(30) do |slice|
      sh ASTYLE, '-Q', '--options=.astyle', *slice, verbose: false
    end
  end

  desc '*.rbファイルを整形する'
  task :ruby do
    raise '文字コードをUTF-8にしてください(chcp 65001 など)' if Encoding.default_external != Encoding::UTF_8
    sh 'rubocop', '-a', 'Tools', 'Rakefile', *FileList['Tools/Rakefiles/*.rake']
  end

end
